version: "2"

linters:
  default: standard
  enable:
    - copyloopvar
    - errname
    - errorlint
    - exhaustive
    - gocritic
    - gosec
    - intrange
    - misspell
    - nilerr
    - nolintlint
    - unconvert
    - unparam
    - usestdlibvars
  settings:
    exhaustive:
      default-signifies-exhaustive: true
    nolintlint:
      require-explanation: true

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/The127/beanstore
